sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rezride/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rezride/react-test npm test

after_success:
  - docker build -t rezride/multi-client ./client
  - docker build -t rezride/multi-nginx ./nginx
  - docker build -t rezride/multi-server ./server
  - docker build -t rezride/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rezride/multi-client
  - docker push rezride/multi-nginx
  - docker push rezride/multi-server
  - docker push rezride/multi-worker

deploy:
  provider: elasticbeanstalk
  regions: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-413123695639
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
